module.exports = {
    apps: [{
        name: "lantu-server",
        script: "./app.js",
        instances: 4,
        exec_mode: 'cluster',
        env_production: {
            CHROME_EXECUTEABLE_PATH: '',
            NODE_ENV: "production",
            WECHAT_APPID: "",
            WECHAT_APPSECRET: "",
            MONGO_URI: "",
            REPLICA_SET: '',
            DATA_BASE_NAME: '',
            APP_ID: "",
            APP_NAME: "",
            SSL_FORCE: true,
            SERVER_DOMAIN: "",
            SERVER_PORT: "",
            SERVER_NAME: "",
            MASTER_KEY: "",
            SMTP_USER: "",
            SMTP_PASSWORD: "",
            SMTP_HOST: "",
            SMTP_PORT: "",
            MANAGER_USER: "",
            MANAGER_PASSWORD: "",
            COMPANY_NAME: "",
            COMPANY_SHORT_NAME: "",
            CLIENT_URL: "",
            OSS_REGION: '',
            OSS_KEY: '',
            OSS_SECRET: '',
            BUCKET: '',

            ALIPAY_APP_ID: '',
            ALIPAY_NOTIFY_URL: '',
            ALIPAY_KEY: '',
            ALIPAY_RSA_PRIVATE: '',
            ALIPAY_RSA_PUBLIC: '',
            ALIPAY_TIMEOUT: '',
            ALIPAY_URL: '',
            ALIPAY_RETURN_URL: '',

            WEPAY_NOTIFY_URL: '',
            WEPAY_KEY: '',
            WEPAY_MECH_ID: '',
            WEPAY_APP_ID: '',
            WEPAY_CERTIFICATE: '',
        }
    }]
}